// <auto-generated />
namespace NguyenTung_8933.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202303220635497_Fix DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
